#!/usr/bin/env bash

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
project_root="$(cd "${script_dir}/.." && pwd)"
input_path="${1:-${project_root}/assets/detention-stints_summary.parquet}"
output_path="${2:-${project_root}/assets/facility-weekly-data.js}"

if ! command -v duckdb >/dev/null 2>&1; then
  echo "Error: the DuckDB CLI is required but was not found." >&2
  echo "Install DuckDB, then run this script again." >&2
  exit 1
fi

if [[ ! -f "${input_path}" ]]; then
  echo "Error: Parquet input not found: ${input_path}" >&2
  exit 1
fi

output_dir="$(dirname "${output_path}")"
mkdir -p "${output_dir}"

temporary_dir="$(mktemp -d "${output_dir}/facility-data.XXXXXX")"
temporary_output="${temporary_dir}/facility-weekly-data.js"
trap 'rm -rf "${temporary_dir}"' EXIT

# Escape apostrophes before interpolating paths into DuckDB string literals.
input_sql_path="${input_path//\'/\'\'}"
output_sql_path="${temporary_output//\'/\'\'}"

# Control characters keep DuckDB's CSV writer from quoting the single output
# field, leaving a valid JavaScript assignment in the generated file.
duckdb_delimiter=$'\003'
duckdb_quote=$'\001'
duckdb_escape=$'\002'

duckdb -c "
COPY (
  SELECT
    '/* Generated by scripts/build-facility-weekly-data.sh; do not edit directly. */ window.facilityWeeklyData = '
    || to_json(
      list(
        struct_pack(
          code := code,
          name := name,
          city := city,
          latitude := latitude,
          longitude := longitude,
          weekly := weekly
        )
        ORDER BY
          CASE WHEN code = 'NRLKCMI' THEN 0 ELSE 1 END,
          name
      )
    )
    || ';'
  FROM (
    SELECT
      detention_facility_code AS code,
      any_value(facility_name) AS name,
      coalesce(any_value(facility_city), '') AS city,
      any_value(facility_latitude) AS latitude,
      any_value(facility_longitude) AS longitude,
      list(
        struct_pack(
          date := strftime(bucket, '%Y-%m-%d'),
          count := round(n)::INTEGER
        )
        ORDER BY bucket
      ) AS weekly
    FROM read_parquet('${input_sql_path}')
    GROUP BY detention_facility_code
  )
)
TO '${output_sql_path}' (
  FORMAT CSV,
  HEADER FALSE,
  DELIMITER '${duckdb_delimiter}',
  QUOTE '${duckdb_quote}',
  ESCAPE '${duckdb_escape}'
);
"

mv "${temporary_output}" "${output_path}"
echo "Generated ${output_path} from ${input_path}"
